---
title: "rSurveyAssign: tools for simulation of assignment in web surveys"
author: "Shigeru ONO"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{rSurveyAssign: tools for simulation of assignment in web surveys}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`rSurveyAssign`パッケージは、web調査における対象者割付についてのシミュレーションを行うためのパッケージです。

このパッケージを使うと、ある種の対象者割付を行うweb調査について、必要な標本サイズを見積もったり、割付によって生じるバイアスを評価したりすることができます。また、すでに行った調査について、集計時にバイアスを取り除くためのウェイトを求めることもできます。

ここでは、`rSurveyAssign`パッケージの背後にある考え方と、パッケージの用途について説明します。

## 1. このパッケージが想定する調査

対象者割付とは、調査対象者を異なる提示物や設問に対して配分することを指します。
以下では提示物や設問を「刺激」と呼びます。

このパッケージは、次の４つの要件を持つ調査のためのパッケージです。

1. 各刺激に対し、刺激ごとに設定された条件を満たす対象者を割り付け、その人々から回答を集めたい
2. 対象者を割り付ける刺激の数に上限を設けたい
3. 各刺激について、目標とする割付人数を達成したい
4. 調査対象者数をできるだけ減らしたい

### 1.1 事例: ブランド・イメージ調査

上記の４つの要件を持つ調査は、web調査の実務において数多く見られます。
説明のため、もっともわかりやすい例を挙げましょう。

ある製品カテゴリにおける10個のブランドについて、消費者が抱いているイメージを
調べたい、という場面について考えます。

1. あるブランドのイメージを聴取する対象者は、そのブランドを知っている人であるとします。
2. 調査負荷の観点から、ひとりの対象者に対して聴取できるブランドの数は2個までとしたいです。
3. 各ブランドについて、少なくとも100人から回答を得たいです。
4. 調査コストの観点から、調査対象者数をできるだけ減らしたいと思います。

このブランド・イメージ調査の手続きについて考えてみましょう。
まず、次の手続きが考えられます。

- **調査手続き1. すべてのブランドに割り付ける**
  - 対象者にあるひとつのブランドを提示し、そのブランドのイメージについて聴取します。
    これを、10個すべてのブランドについて繰り返します。
    
この手続きでは、各対象者にその人の知らないブランドについても聴取することになりますし、
対象者はブランド・イメージについての回答を10回繰り返す事になります。
すなわち、要件1,2が満たされていません。
そこで、次の手続きを考えます。

- **調査手続き2. 2個のブランドに割り付ける**
  - それぞれの対象者について、その人に提示するブランドを3個選びます。
    すなわち、対象者を2個のブランドに**割り付け**ます。
  - 対象者に割り付けられた2個のブランドのうちひとつを提示し、そのブランドのイメージを聴取します。
    これを2個のブランドについて繰り返します。

この手続きでは、要件2は満たされましたが、要件1はいまだ満たされていません。
今度は次のような手続きを考えます。

- **調査手続き3. 知っているすべてのブランドに割り付ける**
  - それぞれの対象者に、10個のブランドのリストを提示し、知っているブランドはどれかを聴取します。
  - それぞれの対象者を、その人が知っているすべてのブランドに**割り付け**ます。
    いずれのブランドについても知らないと答えた人については聴取を終了します。
  - 対象者に、割り付けられたブランドのうちひとつを提示し、そのブランドのイメージを聴取します。
    これを、その人が割り付けられたすべてのブランド(=その人が知っているすべてのブランド)について繰り返します。

この手続きでは、要件1は満たされましたが、要件2が満たされていません。
そこで、次のような手続きを考えます。

- **調査手続き4. 知っているブランドのうち1個～2個に割り付ける**
  - それぞれの対象者に、10個のブランドのリストを提示し、知っているブランドはどれかを聴取します。
  - それぞれの対象者を、その人が知っているブランドのうち1個～2個のブランドに**割り付け**ます。
    いずれのブランドについても知らないと答えた人については聴取を終了します。
  - 割り付けられたブランドのうちひとつを提示し、
    購入意向を聴取します。これを、割り付けられたブランドについて繰り返します。

こうして、要件1, 2を同時に満たす調査手続きにたどり着きました。

このように、対象者の回答(各ブランドを知っているかどうか)に応じてその後の設問を変更する手続きは、古典的な質問紙調査では困難でした。web調査ならではの調査手続きといえるでしょう。

### 1.2 調査手続きの性質


調査手続き4.は、いっけん良い手続きのようにみえます。しかしこの手続きは、次の2つの深刻な問題点を持っています。

- 必要な対象者数がわからない
- 回答の集計値がバイアスを持つ

#### 問題点1. 必要な対象者数がわからない

それぞれのブランドについて、目標とする件数の回答を集めたとき(要件3を満たしたとき)、
どの程度の対象者数が必要でしょうか。

- 調査手続き1.では、$N$人の対象者に調査すれば、各ブランドについて$N$件の回答が得られます。
- 調査手続き2.では、$N$人の対象者に調査すれば、全ブランドを通じて延べ $N \times L$ 件の回答が得られます。ブランドへの割付をバランス良く行えば、各ブランドについて $(N \times L) / K$ 件の回答が得られるはずです。
- 調査手続き3.では、対象者があるブランドについて知っている割合を$P$としたとき、そのブランドについて $N \times P$ 件の回答が得られます。事前に別の情報源から $P$ を推測できれば、十分な件数の回答を得るために必要な対象者数を逆算することができるでしょう。
- しかし調査手続き4.では、各ブランドについて何件の回答が得られるかを事前に推測することが困難です。

#### 問題点2. 回答の集計値がバイアスを持つ

調査手続き4.によって得た回答がどのような性質を持つか、簡単な例を通じて考えてみましょう。

調査対象のブランドを{a,b,c}の3つとしましょう。aについて知っている対象者に注目すると、
対象者たちは下表の4種類に分かれます。

aについて  bについて   cについて  
---------- ----------- -----------
知っている 知らない    知らない   
知っている 知っている  知らない   
知っている 知らない    知っている 
知っている 知っている  知っている 

調査手続き4.による調査を想定します。
各対象者の割付ブランド数の最大値を2としたとき、aについて知っている人が
aに割り付けられる確率はどうなるでしょうか。

仮に、割付ブランドをその対象者が知っているブランドのなかから等確率に選ぶとすると、
下表となります。

aについて  bについて   cについて   aに割り付けられる確率 
---------- ----------- ----------- ----------------------
知っている 知らない    知らない    $1$
知っている 知っている  知らない    $1$
知っている 知らない    知っている  $1$
知っている 知っている  知っている  $2/3$

a以外のブランド(bとc)のうち、知っているブランドの個数が0から1の人は、
必ずaに割り付けられます。
いっぽう、個数が2の人(a,b,cのすべてを知っている人)がaに割り付けられる確率は$2/3$
しかありません。

従って、この調査手続きで集めたaについての回答は、aについて知っている人々のうち、
他のブランドを知らない人々の回答へと偏ることになります。

多くの場合、あるブランドについての知識や態度は、
その製品カテゴリの他のブランドについて知っている程度と関連しているでしょう。
たとえば、ブランドaに対する購入意向が、
他に多くのブランドを知っているほど低いとしましょう。
このとき、ブランドaの購入意向の回答は高めに偏ることになります。

このような、割付に起因する集計値の偏りを**割付バイアス**と呼ぶことにします。

割付バイアスの大きさは、各ブランドが知られている程度や
割付ブランドの選び方によって複雑に変化します。そのため、推測するのは容易ではありません。
  
## 2 このパッケージの目的

調査対象者に刺激を提示し反応を測定したい一方、個々の対象者に提示できる刺激に制約があるという場面は、調査実務において珍しくありません。回答負荷や調査コストの削減のため、上記の調査手続き4.のような工夫をする場合も多いでしょう。その反面、このような工夫によって、事前の標本サイズ設計は困難になり、調査結果は割付バイアスを持ちます。

`rSurveyAssign`パッケージはこの問題に対処するためのパッケージです。このパッケージは、冒頭に挙げた4つの要件を持つ調査に対して、次の3つの機能を提供します。

- 指定した調査手続きの下で必要となる対象者数を事前に推測する
- 指定した調査手続きの下で生じる割付バイアスを事前に評価する
- 指定した調査手続きの下で得た回答データを集計する際に用いるウェイトを算出する

## 3. このパッケージで用いる用語

### 3.1 カテゴリ・スロット・割付可能性

このパッケージは、次の状況を想定して作られています。

- 1つ以上の「**カテゴリ**」がある。
- あるカテゴリは、1つ以上の「**スロット**」からなる。
- すべてのカテゴリのすべてのスロットについて調査したい。
- それぞれの調査対象者は、それぞれのカテゴリについて「**割付可能**」かそうでないかのいずれかである。
- それぞれの調査対象者は、それぞれのスロットについて「**割付可能**」かそうでないかのいずれかである。
- ある対象者を割り付けることができるカテゴリ・スロットの数には上限がある。

いくつかの例を挙げましょう。

#### 例1

- 消費者が耐久消費財ブランドについて抱いているイメージを調べたい。
- 自動車、白物家電、携帯電話、家具のブランドについて調べることにする。
- 自動車のブランドのうち、トヨタ、日産...などについて調べる。白物家電のうち、日立、パナソニック...などについて調べる。
  このように、各製品カテゴリの複数のブランドについて調べる。
- ある製品カテゴリについて聴取する対象者は、そのカテゴリの使用者に限定したい。
- ある製品カテゴリのあるブランドについてイメージを聴取する対象者は、そのブランドについて知っている人に限定したい。
- ある対象者に聴取できるカテゴリの数とブランドの数に上限を設けたい。

この例では、「カテゴリ」は製品カテゴリ(自動車、白物家電、携帯電話、家具)、
「スロット」はブランド
(トヨタ、日産...、日立、パナソニック...)に対応しています。
下の表を参照してください。

このパッケージでの用語 この例では
---------------------- -----------------------
カテゴリ               製品カテゴリ
カテゴリへの割付可能性 その製品カテゴリを使用しているか
割付カテゴリ数の上限   ある人に最大で何カテゴリまで詳しく訊けるか
スロット               ブランド
スロットへの割付可能性 そのブランドを知っているか
割付スロット数の上限   ある人に最大で何ブランドまで詳しく訊けるか
---------------------- -----------------------

#### 例2

- 数多くの国内観光地について、そこに訪問した人の満足度を調べたい。
- ある対象者にある観光地について訪問時の満足度を訊くためには、
その対象者はその観光地に訪問したことがなければならない。
- ある対象者に満足度を訊くことができる観光地の数には上限がある。

この例では、「スロット」は観光地に対応しています。
「カテゴリ」にあたるものはないので、
ひとつのカテゴリが存在し、すべての対象者がそのカテゴリに
たいして割付可能であると考えます。
下の表を参照してください。

このパッケージでの用語 この例では
---------------------- -----------------------
カテゴリ               (ひとつだけ存在する)
カテゴリへの割付可能性 (すべての対象者が割付可能)
割付カテゴリ数の上限   (1個)
スロット               観光地
スロットへの割付可能性 その観光地にいったことがあるか
割付スロット数の上限   ある人に最大で何か所までの詳しく訊けるか
---------------------- -----------------------

これらは例にすぎません。このパッケージは、「カテゴリ」「スロット」「割付可能性」が
具体的に何を指すのかは問いません。また、割り付けたカテゴリとスロットについてなにを聴取するのかも問いません。

### 3.2 目標対象者数、オープン、クローズド

このパッケージでは、Web調査を想定し、次のように仮定します。

- 調査対象者の調査への参加は逐次的に行われます。すなわち、全員が同時に回答をはじめるのではなく、まちまちのタイミングで回答をはじめます。ある対象者のカテゴリ・スロットへの割付も逐次的に行われます。
- 調査対象者のカテゴリ・スロットへの回答ならびに割付可能性は、調査対象者間で独立です。
- 調査参加順序は確率的な現象であり、ありうるすべての調査参加順序が等しい確率で実現します。すなわち、調査対象者の回答と調査参加順序とのあいだには関連がありません。

以下の用語を導入します。

- それぞれのスロットについて、そのスロットに割り付けたい対象者数が定められています。これを「**目標対象者数**」と呼びます。
- 調査実施中のある時点において、それまでに割り付けられた対象者数が目標対象者数に達していないスロットを「**オープン**」、達しているスロットを「**クローズド**」と形容することにします。
- 調査実施中のある時点において、オープンなスロットが1つ以上あるカテゴリを「**オープン**」、すべてのスロットがクローズドであるカテゴリを「**クローズド**」と形容することにします。

## 4. このパッケージの用途

このパッケージは、上記の手続きによる調査を実施しようと考えている調査者、ないしすでに実施した調査者のためのパッケージです。

このパッケージではさまざまな割付方法について検討することができます。
このパッケージがカバーしている
割付方法の範囲について、["1. How to assign subjects"](vignette_assign.html)を参照して下さい。

このパッケージの用途は次の3つです。

- **標本サイズ推定**
  - 上記の手続きによる調査を**計画しているとき**、
    各スロットについて必要な回答件数を得るためにはどの程度の調査対象者数が必要かを推定する。
  - 使用方法は["2. How to forecast sample size"](vignette_size.html)を参照して下さい。
- **バイアス評価**
  - 上記の手続きによる調査を**計画しているとき**、
    調査結果が持つであろうバイアスを評価する。
  - 使用方法は["3. How to estimate bias"](vignette_bias.html)を参照して下さい。
- **ウェイト算出** 
  - 上記の手続きによる調査を**行ったあとで**、
    集計のためのウェイトを算出する。
  - 使用方法は["4. How to compute survey weights"](vignette_weight.html)を参照して下さい。

なお、このパッケージはweb調査の機能を提供するものではありません。web調査の実施時に対象者をカテゴリ・スロットへと割り付ける機能は、web調査システム上で別途実装する必要があります。
