---
title: "How to assign subjects"
author: "Shigeru ONO"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{How to assign subjects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


["rSurveyAssign: tools for simulation of assignment in web surveys"](vignette.html)で述べたように、
`rSurveyAssign`パッケージは以下の調査手続きを想定します。

1. ある人が調査に参加したとき、その人について、各カテゴリについて割付可能であるかどうかを調べる。
2. **なんらかの方法で**、その対象者のすべての割付可能カテゴリのうちいくつかを選ぶ。
   これを、「対象者をカテゴリに割り付ける」と呼び、
  選択されたカテゴリを「割付カテゴリ」と呼ぶ。もし割付できなかったら、その対象者に
  対する調査は中止する。
3. 対象者に、それぞれの割付カテゴリについて、スロットのリストを提示し、
   それぞれについて割付可能かどうかを調べる。
4. **なんらかの方法で**、その対象者のいずれかの割付カテゴリの割付可能スロットのなかから、いくつかのスロットを選ぶ。
   これを、「対象者をスロットに割り付ける」と表現し、
   選択されたカテゴリを「割付スロット」と呼ぶ。もし割付できなかったら、
   その対象者に対する調査は中止する。
5. 割付スロットについての詳細な設問を提示し、回答を得る。
6. すべてのカテゴリがクローズドになったら、調査を終了する。

この文書では、上記のうち太字部分について説明します。すなわち、Step 2.におけるカテゴリの割付方法、ならびにStep 4.における
スロットの割付方法について説明します。

## 1. カテゴリの割付方法

割付カテゴリを決める方法は、次の4つの特徴によって整理することができます。

- 割付タイプ
- 絞り込み条件
- 順序付け条件
- 除外条件

順に説明します。
以下では、対象者に割り付けるカテゴリの最大数を$J$とします。

#### 割付タイプ
`rSurveyAssign`パッケージでは、割付タイプとして次の2種類を想定します。

- `adaptive`: 適応的方法
  - 各対象者について以下の手順でカテゴリ割付を行います。
  - Step 1.  **絞り込み**: 
    - その人の割付可能カテゴリのなかから、指定した条件
      (絞り込み条件)を満たすカテゴリを選び、割付カテゴリの候補とする。
  - Step 2.  **順序付け**: 
    - 選んだ候補のなかから、指定された優先順位(順序付け条件)に従って
      $J$個までのカテゴリを抜き出し、割付カテゴリとする。
  - Step 3.  **除外**:
    - 割付カテゴリが所定の条件(除外条件)に該当する場合は、割付を中止する。
- `nonadaptive`: 非適応的方法
  - 各対象者について以下の手順で割り付けを行います。
  - Step 1. **順序付け**:
    - その対象者にとっての割付可能性は無視し、すべてのカテゴリのなかから、指定された優先順位(順序付け条件)に従って$J$個までのカテゴリを抜き出し、割付カテゴリの候補とする。
  - Step 2. **絞り込み**: 
    - 抜き出されたカテゴリのなかから、指定した条件(絞り込み条件)に該当するカテゴリを選び、割付カテゴリとする。
  - Step 3. **除外**: 
    - 割付カテゴリが所定の条件(除外条件)に該当する場合は、割付を中止する。
     
ふたつの割付タイプは、絞り込みを先に行うか、順序付けを先に行うかという点が違います。

- 適応的な方法では、まず割付可能なカテゴリに絞り込み、それらのなかから優先順位の高い
  $J$個までのカテゴリを抜き出します。
  - これは非適応的方法に比べて効率の良いやり方です。
  - その反面、割付バイアスが生じます。割付可能なカテゴリが多い人は、ある割付可能カテゴリに
    割り付けられる確率が低くなるためです。
- いっぽう非適応的な方法では、まず割付可能性を無視して$J$個までのカテゴリを抜き出してしまい、
  それらを割付可能なカテゴリへと絞り込みます。
  - その結果、割付カテゴリが少なくなってしまったり、
    0個になってしまったりする対象者が出現し、その分だけ多くの調査対象者数を必要とします。
  - その反面、割付バイアスは生じにくくなります。
    ある対象者がある割付可能カテゴリに割り付けられるかどうかが、その対象者の
    他のカテゴリの割付可能性とは独立に決まっているためです。


#### 絞り込み条件
`rSurveyAssign`パッケージでは、絞り込みの条件として次の2種類を想定します。

  - `all`: その対象者の割付可能カテゴリを選ぶ。
    - このとき、割付カテゴリはクローズドでありうる点に注意してください。つまり、すでに目標票数に達しているカテゴリについても聴取する場合が生じます。いいかえれば、「無駄な」回答収集を行うことになります。
  - `open`: その対象者の割付可能カテゴリのうちオープンなカテゴリを選ぶ。
  
どちらを選んでも必要な調査対象者数は変わりませんが、対象者の回答負荷は`all`のほうが高く、また割付バイアスは`open`のほうが強くなると考えられます。
  
#### 順序付け条件
`rSurveyAssign`パッケージでは、順序付けの条件として以下の4種類を想定します。

  - `random`: ランダムに並べる。
  - `openclosed`:   以下の順に並べる。(1)オープンなカテゴリ、ランダム順。
            (2)クローズドなカテゴリ、ランダム順。
  - `shortnum`:   その時点でオープンなスロット数が多いカテゴリから順に並べる。
  - `shortratio`: その時点でオープンなスロットが占める割合が大きいカテゴリから順に並べる。
  
{`shortratio`と`shortnum`}, `open`, `random`の順に、必要な調査対象者数が少なくなり、また
割付バイアスが強くなると考えられます。

#### 除外条件
`rSurveyAssign`パッケージでは、除外の条件として以下の2種類を想定します。

  - `none`: なし。
  - `allclosed`: 割付カテゴリとして選ばれたカテゴリがすべてクローズドであったら、割付しない。
    
絞り込み条件が`open`であるとき、
割付カテゴリはオープンなカテゴリなので、除外条件は意味を持ちません。
絞り込み条件が`all`であるとき、除外条件として`allclosed`を指定すれば、
「割付カテゴリのうち少なくともどれかひとつはオープンでなければならない」と指定したことになります。

#### 組み合わせ

`rSurveyAssign`パッケージは、上で述べた4つの特徴の組み合わせによって生じる
すべての割付方法をサポートしています。参考として、すべての組み合わせを下表に示します。

割り付けるカテゴリの最大数を$J$とします。

割付タイプ     絞り込み条件 順序づけ条件          除外条件           割付カテゴリの選び方
-------------- ------------ --------------------- --------------     --------------
`adaptive`     `all`        `random`              `none`             その対象者の割付可能カテゴリから$J$個までを等確率に選ぶ。
`adaptive`     `all`        `random`              `allclosed`        その対象者の割付可能カテゴリから$J$個までを等確率に選ぶ。選ばれたカテゴリのなかにオープンなカテゴリがなかったら割付しない。
`adaptive`     `all`        `openclosed`          `none`             その対象者の割付可能カテゴリのうちオープンなものから$J$個までを等確率に選ぶ。$J$個選べなかったら、その対象者の割付可能カテゴリのうちクローズドなものから不足個数までを等確率に選ぶ。
`adaptive`     `all`        `openclosed`          `allclosed`        その対象者の割付可能カテゴリのうちオープンなものから$J$個までを等確率に選ぶ。$J$個選べなかったら、その対象者の割付可能カテゴリのうちクローズドなものから不足個数までを等確率に選ぶ。選ばれたカテゴリの中にオープンなカテゴリがなかったら割付しない。
`adaptive`     `all`        `shortnum`            `none`             その対象者の割付可能カテゴリから、オープンなスロットが多い順に$J$個までを選ぶ。
`adaptive`     `all`        `shortnum`            `allclosed`        その対象者の割付可能カテゴリから、オープンなスロットが多い順に$J$個までを選ぶ。選ばれたカテゴリの中にオープンなカテゴリがなかったら割付しない。
`adaptive`     `all`        `shortratio`          `none`             その対象者の割付可能カテゴリのうち、オープンなスロットが占める割合が高い順に$J$個までを選ぶ。
`adaptive`     `all`        `shortratio`          `allclosed`        その対象者の割付可能カテゴリのうち、オープンなスロットが占める割合が高い順に$J$個までを選ぶ。選ばれたカテゴリの中にオープンなカテゴリがなかったら割付しない。
`adaptive`     `open`       `random`,`openclosed` `none`,`allclosed` その対象者のオープンな割付可能カテゴリから$J$個までを等確率に選ぶ。
`adaptive`     `open`       `shortnum`            `none`,`allclosed` その対象者のオープンな割付可能カテゴリから、オープンなスロットが多い順に$J$個までを選ぶ。
`adaptive`     `open`       `shortratio`          `none`,`allclosed` その対象者のオープンな割付可能カテゴリから、オープンなスロットが占める割合が高い順に$J$個までを選ぶ。
`nonadaptive`  `all`        `random`              `none`             すべてのカテゴリから$J$個を等確率に抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `all`        `random`              `allclosed`        すべてのカテゴリから$J$個を等確率に抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。選ばれたカテゴリのなかにオープンなカテゴリがなかったら割付しない。
`nonadaptive`  `all`        `openclosed`          `none`             オープンなカテゴリから$J$個までを等確率に抜き出す。$J$個抜き出せなかったら、クローズドなカテゴリから不足個数までを等確率に抜き出す。抜き出したカテゴリのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `all`        `openclosed`          `allclosed`        オープンなカテゴリから$J$個までを等確率に抜き出す。$J$個抜き出せなかったら、クローズドなカテゴリから不足個数までを等確率に抜き出す。抜き出したカテゴリのなかからその対象者の割付可能カテゴリを選ぶ。選ばれたカテゴリの中にオープンなカテゴリがなかったら割付しない。
`nonadaptive`  `all`        `shortnum`            `none`             すべてのカテゴリから、オープンなスロットが多い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `all`        `shortnum`            `allclosed`        すべてのカテゴリから、オープンなスロットが多い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。選ばれたカテゴリのなかにオープンなカテゴリがなかったら割付しない。
`nonadaptive`  `all`        `shortratio`          `none`             すべてのカテゴリから、オープンなスロットが占める割合が高い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `all`        `shortratio`          `allclosed`        すべてのカテゴリから、オープンなスロットが占める割合が高い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。選ばれたカテゴリの中にオープンなカテゴリがなかったら割付しない。
`nonadaptive`  `open`       `random`,`openclosed` `none`,`allclosed` オープンなカテゴリから$J$個までを等確率に抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `open`       `shortnum`            `none`,`allclosed` オープンなカテゴリからオープンなスロットが多い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。
`nonadaptive`  `open`       `shortratio`          `none`,`allclosed` オープンなカテゴリからオープンなスロットが占める割合が高い順に$J$個までを抜き出し、そのなかからその対象者の割付可能カテゴリを選ぶ。

## 2. スロットの割付方法

**Step 4.**で割付スロットを決める方法は、割付カテゴリを決める場合と同様です。
説明を以下のように読み替えてください。

- 「カテゴリ」→「スロット」
- 「その時点でオープンなスロット数が多いカテゴリ」→「その時点で目標票数に対して不足している票数が多いスロット」
- 「その時点でオープンなスロットが占める割合が多いカテゴリ」→「その時点で目標票数に対して不足している票数の割合が高いスロット」

## 3. 割付スロット決定に際してのカテゴリの決定方法

**Step 4.**で割付スロットを決める際、もし**Step 2.**で複数個のカテゴリへの割付が生じていたら、
割付スロットをどの割付カテゴリから選ぶかという問題が生じます。

現バージョンの`rSurveyAssign`パッケージは、以下に述べる方法のみを想定しています。

- 割付カテゴリのなかからひとつを等確率に選び、そのカテゴリにおいて、前項で説明した方法でスロットへと割り付ける。
- スロット割付ができなかったら、他の割付カテゴリのなかからひとつを等確率に選び、そのカテゴリにおいてスロットへと割り付ける。これを繰り返し、どこかのカテゴリでスロット割付ができるまで続ける。
- どの割付カテゴリでもスロット割付ができなかったら、その対象者に対する調査を中止する。

ある対象者の割付スロットは、必ず同一カテゴリのスロットとなります。

## 4. 割付に伴うバイアスはいつ生じるか

割付バイアスはどのような場面で生じるでしょうか。

まず、すべての対象者がすべてのカテゴリとスロットに割付可能である場合には、上記に述べたどの方法で割り付けを行っても、
割付バイアスは生じませんし、そもそも`rSurveyAssign`パッケージを使う理由がありません。
以下では、いずれかの対象者において割付不能なカテゴリないしスロットが存在する場合について考えます。

カテゴリについての回答において割付バイアスが**生じない**のは、割付方法が以下の条件をすべて満たすときに限られます。他の方法ではなんらかのバイアスが生じることになります。

- カテゴリ割付において非適応的方法を選んでいるか、割付カテゴリの最大数が十分に大きく、順序付けに意味がなくなっている
- カテゴリ割付において除外条件をnoneにしている

スロットについての回答において割付バイアスが**生じない**のは、割付方法が以下の条件をすべて満たすときに限られます。他の方法ではなんらかのバイアスが生じることになります。

- 割付カテゴリの最大数を1にしている
- スロット割付において非適応的方法を選んでいるか、割付スロットの最大数が十分に大きく、順序付けに意味がなくなっている
- スロット割付において除外条件をnoneにしている

